import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "scripts/**",
    // Generated by `stellar contract bindings typescript` during deploy.sh.
    // Not authored here, not imported by the app, and it does not satisfy the
    // project's lint rules — linting it fails CI after every contract deploy.
    "packages/**",
  ]),
]);

export default eslintConfig;
