name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rust-contract:
    name: Build & Test Smart Contract
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32v1-none

      - name: Run Cargo Test
        run: cargo test
        working-directory: contract

      - name: Build Contract WASM
        run: cargo build --target wasm32v1-none --release
        working-directory: contract

  nextjs-frontend:
    name: Build & Test Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install Dependencies
        run: npm install
        working-directory: client

      - name: Run Tests
        run: npm run test
        working-directory: client

      - name: Build Frontend
        run: npm run build
        working-directory: client
        env:
          NEXT_PUBLIC_STELLAR_NETWORK: testnet
          NEXT_PUBLIC_STELLAR_NETWORK_PASSPHRASE: "Test SDF Network ; September 2015"
          NEXT_PUBLIC_STELLAR_RPC_URL: https://soroban-testnet.stellar.org
          NEXT_PUBLIC_CONTRACT_ADDRESS: CBMYQYSWFPCXG5B5WXC73P4V6WR765EGA2YSMMSNM32I47Q4YYAQDXFE
